aulastec/base/urls.py
from django.urls import path

from aulastec.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

aulastec/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aulastec.base.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

aulastec/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App baser User class.

    Email and password are required. Other fields are optional.
    """
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

aulastec/base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html')

aulastec/base/templates/base/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Treinamentos TecAcademy</title>

    <meta name="description" content="Página de Acesso aos Treinamentos do uso da Plataforma">
    <meta name="author" content="Walter Schmidt Silva">

    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>


</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'base:home' %}">Página de Acesso aos Treinamentos do uso da Plataforma</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

        </ul>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-12">

            <div class="jumbotron">
                <!--
                <h1>
                    TecAcademy Digital Consulting
                </h1>
                -->
                <h2>
                    Plataforma de Acompanhamento e Avaliação Qualitativa
                </h2>
                <p>
                    Aqui você encontra todos os vídeos explicativos sobre o uso da plataforam de acompanhamento e
                    avaliação qualitativa da TecAcademy.
                </p>

                <h6 class="mt-4">Já é usuário da plataforma da TecAcademy e ainda não tem o seu login de acesso?
                    <br>Então preencha o formulário abaixo com o seu nome, Endereço de E-mail e Celular para receber
                    o seu Usuário e Senha de acesso aos treinamentos.</h6>

                <form action="https://tecacademy.us2.list-manage.com/subscribe/post?u=e95c8072d62d467bbb725dd46&amp;id=f4464d90e7"
                      method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
                      class="form-row align-items-center" target="_blank" novalidate>
                    <div class="form-row align-items-center">
                        <div class="col-auto">
                            <label class="sr-only" for="mce-FNAME">Email</label>
                            <input type="text" value="" name="FNAME" class="form-control" id="mce-FNAME"
                                   placeholder="Digite seu Nome">
                        </div>
                        <div class="col-auto">
                            <label class="sr-only" for="mce-EMAIL">Nome</label>
                            <input type="email" value="" name="EMAIL" class="form-control required email" id="mce-EMAIL"
                                   placeholder="Digite seu E-mail">
                        </div>

                        <div class="col-auto">
                            <label class="sr-only" for="mce-PHONE">Celular</label>
                            <input type="text" name="PHONE" class="form-control" value="" id="mce-PHONE"
                                   placeholder="Digite seu Celular">
                        </div>

                        <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                        <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text"
                                                                                                  name="b_e95c8072d62d467bbb725dd46_f4464d90e7"
                                                                                                  tabindex="-1"
                                                                                                  value=""></div>

                        <div class="col-auto">
                            <input type="submit" value="Enviar" name="subscribe"
                                   id="mc-embedded-subscribe" class="btn btn-primary">
                        </div>
                    </div>
                </form>

            </div>
            <br>
            <h1>
                Conheça a Equipe da TecAcademy
            </h1>
            <br>

            <div class="row">
                <div class="col-md-4">
                    <div class="card">
                        <h5 class="card-header">
                            Paula Lameu
                        </h5>
                        <div class="card-body">
                            <p class="card-text">
                                <img src="{% static 'img/PaulaNew.png' %}" alt="Foto de Paula Lameu"
                                     class="img-thumbnail float-left mr-3"/>
                            <div align="justify">
                                Doutora pelo PhD Research Program da School of Education da University of Birmingham,
                                UK, é Mestre pelo Programa de Estudos Linguísticos e Literários em Inglês, do
                                Departamento de Letras Modernas da Faculdade de Filosofia, Letras e Ciências Humanas da
                                Universidade de São Paulo (FFLCH/USP). Especialista em Comunicação Jornalística em
                                Mídias Digitais pela Pontifícia Universidade Católica de São Paulo (PUC/SP), foi
                                professora de Linguística e Sociolinguística na Faculdade Guaianás, Linguística e
                                Literatura Norte-Americana na Universidade Braz Cubas, Língua Inglesa para o Ensino
                                Fundamental II e Médio da Escola Pueri Domus e professora de Língua Inglesa no CCAA de
                                Mogi das Cruzes. Também atuou como professora de Língua Inglesa para todos os segmentos
                                no Colégio Integração e como Coordenadora Pedagógica de Ensino Fundamental I e II. Hoje
                                atua em duas frentes de pesquisa: a primeira aborda o uso das Novas Tecnologias em sala
                                de aula sob a perspectiva da Assemblage Theory, envolvendo processos discursivos, de
                                ensino, de aprendizagem, políticos, sociais, culturais e históricos, além da construção
                                do sujeito; a segunda compreende o desenvolvimento de currículo personalizado para
                                crianças de Educação Infantil e Ensino Fundamental, que demandam um percurso
                                diferenciado de aprendizagem, sejam eles portadores de necessidades educativas especiais
                                ou não. Possui graduação em Comunicação com habilitação: Jornalismo pela Universidade de
                                Mogi das Cruzes (2000), em Letras (LP/LI), pela Universidade Braz Cubas (2007) e
                                Pedagogia pelas Faculdades Claretianas de Batatais (2009)
                            </div>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <h5 class="card-header">
                            Amanda Longo
                        </h5>
                        <div class="card-body">
                            <p class="card-text">
                                <img src="{% static 'img/Amanda.png' %}" alt="Foto de Amanda Longo"
                                     class="img-thumbnail float-left mr-3"/>
                            <div align="justify">
                                Sou Amanda Longo graduada em Pedagogia, pós graduada em Psicopedagogia.
                                Já atuei na área da Educação, como professora polivalente por 9 anos, com vendas
                                informal, como representante comercial em uma empresa ligada à Educação , mapeando e
                                prospectando mercado em busca de novos negócios. Hoje, faço atendimentos
                                psicopedagógicos, com a função de assessorar e esclarecer a escola sobre os diversos
                                aspectos do ensino aprendizagem da criança, atuando de forma preventiva em cada
                                caso,
                                para analisar e assinalar fatores que favorecem, interferem e prejudicam a
                                aprendizagem
                                de uma criança. Elaboro materiais adaptados para as escolas e pais que desejam
                                intensificar a aprendizagem do seu filho em casa e criação de jogos educativos e
                                pedagógicos.
                            </div>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <h5 class="card-header">
                            Georgia Seara
                        </h5>
                        <div class="card-body">
                            <p class="card-text">
                                <img src="{% static 'img/Georgia.png' %}" alt="Foto de Georgia Seara"
                                     class="img-thumbnail float-left mr-3"/>
                            <div align="justify">
                                Tenho como objetivo profissional trabalhar como Auxiliar de Desenvolvimento
                                Infantil,
                                Professora ou Acompanhante Terapêutica
                            </div>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<footer class="main-footer mt-5 pt-4 text-light">
    <div class="container">
        <div class="row">
            <div class="col">
                <h3> Entre em contato</h3>
                <address>
                    WhatsApp: +55 11 98829-3184
                    <br/>
                    <a href="mailto:contato@tecacademy.com.br" class="text-light">Dúvidas? Envie um e-mail para nós
                        gente clicando aqui!</a>
                    <p>
                        <a class="btn btn-primary btn-large" href="https://www.tecacademy.com.br" target="_blank">Site
                            TecAcademy</a>
                    </p>
                    <p>
                        <a class="btn btn-primary btn-large" href="https://plataforma.tecacademy.com.br"
                           target="_blank">Plataforma de Acompanhamento e Avaliação Qualitativa</a>
                    </p>
                </address>

            </div>

        </div>
    </div>

    <div class="rights pb-4">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% now 'Y' %} Walter Schmidt Silva - TecAcademy Digital Consulting. Todos Direitos Reservados.
                </div>
            </div>
        </div>
    </div>


</footer>

</body>
</html>